### PR TITLE
Add CAST for Firebird

### PR DESCRIPTION
**Pull request by donnykurnia**
Reference:
http://tracker.firebirdsql.org/browse/CORE-3559

### CODE REVIEW

**Comment by yajra** [comment]
Looks fine for me. One question though, does `VARCHAR(255)` is enough? What if the column has more than 255 bytes? Not using firebird so I'm not really sure about it. Thanks!

**Comment by donnykurnia** [comment]
@yajra In my current project, it's enough. In Firebird, [maximum VARCHAR is 32765] (http://www.firebirdsql.org/manual/migration-mssql-data-types.html)

Firebird don't have TEXT type like in psql, only blob, but blob feature in [laravel driver](https://github.com/jacquestvanzuydam/laravel-firebird) is buggy so I'm avoiding it right now.

**Comment by yajra** [comment]
Ok, will accept this for a start. Thanks!

**Comment by yajra** [comment]
Merged and release on v6.11.2. Thanks! 👍

**Pull request merged**
