### PR TITLE
[9.0] Fix deprecated helper functions, then add support for Laravel 6.

### PR DESCRIPTION
**Pull request by lloricode**

### CODE REVIEW

**Comment by yajra** [comment]
Looks good, will the laravel changes first and will try to get back to this asap. Thanks!

**Comment by yajra** [comment]
Aside from deprecated helpers, it seems like there are no other breaking changes that may affect the package. PR good to go. 🍻

**Comment by lloricode** [comment]
@yajra thanks :+1:

**Comment by yajra** [comment]
Released on v9.6.0 🚀 thanks! Moving to other packages...

**Pull request merged**
