### PR TITLE
[6.0] Display url and A balise as hyperlink in excel export

### PR DESCRIPTION
**Pull request by julianfox**
Following the feature request: #1070

### CODE REVIEW

**Comment by yajra** [comment]
Thanks, will review this as soon as I can. 👍

**Comment by yajra** [comment]
@julianfox I made some test and I think there is some minor issue on exporting the link to excel.

As per testing, I converted the id to link. The link was exported successfully but the value of the id was also changed using the link path.

Example output:

```
| http://datatables.dev | Elmore Howe | kgreenfelder@bode.com |
| http://datatables.dev | Ashley Johnston	| mharber@yahoo.com |
```

Expected:

```
| 1 > with link to http://datatables.dev | Elmore Howe | kgreenfelder@bode.com |
| 2 > with link to http://datatables.dev | Ashley Johnston	| mharber@yahoo.com |
```

**Comment by julianfox** [comment]
Yes, it's a normal behaviour, because in my case, we use font awesome icon as value in the datatables. But yes in most of the cases that make sense to keep the original value I'll fix it as soon as I can 👍

**Comment by julianfox** [comment]
I just did an update.

I use the balise a text value as excel file cell value now, only if the balise a text value is a string.
If the balise a text value is html (e.g. button), I use the href value as cell value.

**Comment by yajra** [comment]
Works like a charm. Can you please also send the same PR to https://github.com/yajra/laravel-datatables-buttons if possible for same support on v7? 

Released on v6.28.0 🚀  Thanks!

**Comment by julianfox** [comment]
Ok I will check it as soon as I can

**Pull request merged**
