### PR TITLE
Fix to allow join of eager loaded column based on a HasMany-relationship

### PR DESCRIPTION
**Pull request by SRautila**
Hi

I was having issues implementing column search for a column showing data from a eager loaded HasMany-relationship. Treating HasMany in the same way as HasOne fixed it for me as HasMany has the getForeignKey()-method as well.

See the issue i created: #732

### CODE REVIEW

**Comment by yajra** [comment]
Merged and released on v6.18.1. Thanks a lot! 👍

**Comment by ssipos90** [comment]
Those two classes extend a base class:
`if ($model instanceof HasOneOrMany) {`

**Comment by yajra** [comment]
@ssipos90 good point, didn't notice that. Is it like that since Laravel 5.0? Can you send a PR to refactor it for proper credits on contributions? Thanks!

**Comment by ssipos90** [comment]
Since 4.x

**Comment by ssipos90** [comment]
No credits needed, you do it, please! :D

**Pull request merged**
