### PR TITLE
fix: Error when setting language config for "editor"

### PR DESCRIPTION
**Pull request by OzanKurt**

### CODE REVIEW

**Review by yajra — DISMISSED** [review]

**Comment by yajra** [comment]
The changes break the editor integration on my starter application with the following error:

```js
Uncaught TypeError: editor.one is not a function
```

Can you please provide snippets to replicate the issue that this fixes?

**Comment by OzanKurt** [comment]
> The changes break the editor integration on my starter application with the following error:
> 
> ```js
> Uncaught TypeError: editor.one is not a function
> ```
> 
> Can you please provide snippets to replicate the issue that this fixes?

My code simply adds language array to the config, have a look.

```php

        try {
            $language = json_decode(file_get_contents(resource_path("lang/vendor/datatables/{$locale}.json")), true, 512, JSON_THROW_ON_ERROR);
        } catch (Exception $e) {
            $language = [];
        }

        $language = array_merge_recursive($language, [
            'buttons' => [
                'reload' => __('Reload'),
                'export' => __('Export'),
            ],
            'lengthMenu' => '_MENU_',
            'sSearch' => '',
            'sSearchPlaceholder' => __('Search...'),
        ]);

        /** This part fixes the info text. */
        unset($language['select']['cells'], $language['select']['columns']);

        $builder->language($language);
```

Since the json file contains a key called "editor" it's causing problems when parameterizing.

```js
{
    // ...
    "editor": {
        "close": "Close",
        "create": {
            "button": "New",
            "title": "Create new entry",
            "submit": "Create"
        },
        // ...
    }
}

**Comment by OzanKurt** [comment]
Found a workaround :)

It's a bit cheaty but I believe this gives us the best chances.

```php
if (Str::startsWith($key, 'language.')) {
    return false;
}
```

**Comment by OzanKurt** [comment]
This should work 99.9% of the time now. 😄

**Comment by yajra** [comment]
Thanks, will check this as soon as I can.

**Review by yajra — APPROVED** [review]

**Comment by yajra** [comment]
Apologies for late review, released on https://github.com/yajra/laravel-datatables/releases/tag/v10.4.1 🚀

**Pull request merged**
