### PR TITLE
Support Laravel 7

### PR DESCRIPTION
**Pull request by barryvdh**
Laravel 7 is coming next week, so updated this to prepare/test with L7

### CODE REVIEW

**Comment by barryvdh** [comment]
Related: https://github.com/yajra/laravel-datatables-html/pull/124 and https://github.com/yajra/laravel-datatables-buttons/pull/102

**Comment by yajra** [comment]
Thanks for the heads up, will check Laravel 7 changes and review its compatibility with the current version.

**Comment by yajra** [comment]
Seems like there are no changes that will break the package based on the [upgrade guide](https://laravel.com/docs/master/upgrade). Will try a new installation later.

**Comment by sangnguyenplus** [comment]
@yajra is it okay to merge? Laravel will be released today.

**Comment by yajra** [comment]
@sangnguyenplus were you able to try this on Laravel 7? I wasn't able to do so yet.

**Comment by sangnguyenplus** [comment]
@yajra Sorry, I didn't test it on Laravel 7. Just ask you if you have tested it.

**Comment by adiletmaks** [comment]
@yajra when you can merge it ?

**Comment by yajra** [comment]
Released on v9.9.0. Thanks!

**Comment by barryvdh** [comment]
Thanks!

**Pull request merged**
