### PR TITLE
Added Laravel 5.6 Support

### PR DESCRIPTION
**Pull request by marcoocram**

### CODE REVIEW

**Comment by lloricode** [comment]
im so late :D #1611

**Comment by yajra** [comment]
We already have support for 5.6 on the master branch but I haven't checked 5.6 yet. Will check this over the weekend. Sorry for the delay, don't have time to check this yet. :)

**Comment by lloricode** [comment]
im waiting for this :)

**Comment by publiux** [comment]
dev-master does have support for Laravel 5.6, but it is not published to packagist and can't be used in composer as an identifiable version for production. I suggest you publish 8.3.4 on with the current dev-master, or merge this into the 8.0 branch and publish 8.3.4 from that.

**Comment by yajra** [comment]
Released on v8.4.0, thanks a lot!

**Pull request merged**
