### PR TITLE
Fixed row variables (like DT_RowClass) was not set

### PR DESCRIPTION
**Pull request by Mevrael**
Updated DataProcessor.php to fix row variable names (returned row array keys, for example, DT_RowClass) was set to numeric key.

### CODE REVIEW

**Comment by yajra** [comment]
@Mevrael, thanks for this PR but I think this may cause some issue when we used a value like `setRowClass('id')` for instance and was removed via `removeColumn('id')`.  Can you please paste some snippets to reproduce this issue?

**Comment by Mevrael** [comment]
@yajra, I see. Here is an example.

yajra/laravel-datatables-oracle       v5.8.2

https://gist.github.com/Mevrael/330c816c1cc806e9eef1

set_row_class was not working at all. When I investigated json I found problem at DataProcessor.php. Probably because of Arr::flatten array key DT_RowClass was renamed to 6.

**Comment by yajra** [comment]
Oic, you are not using an object response `make(true)`. Will check this as soon as I can. Thanks for the info!

**Comment by yajra** [comment]
@Mevrael, patch to fix this issue released on v5.8.6 Thanks!

**Pull request closed without merging**
