### PR TITLE
[6.0] Add support ordering when search in nested relations.

### PR DESCRIPTION
**Pull request by ethaizone**
I did it!!

### CODE REVIEW

**Comment by ethaizone** [comment]
Need #849 when you allow field that can be ambiguous to searchable,

**Comment by yajra** [comment]
Thanks a lot! Will try to review and test this asap along with the other PR. 💯

**Comment by ethaizone** [comment]
This PR is next part from #841. At that PR I just not test correct so I cannot cause bug but when I work at next day, my workmate got the error from sort in nested relation when search. I said "Really?", I repeat bug and fix this bug. LOL

Note for another ppl can understand why I just put short description. LOL

**Comment by yajra** [comment]
@ethaizone FYI, I made some test with this PR and found some issues. I made some fixes earlier and and hopefully will be able to release this by next week. ATM, will keep this open until I've completed the fix. Thanks!

**Comment by AdrienPoupa** [comment]
What are the issues please?

**Comment by ethaizone** [comment]
@yajra OMG. I forgot this PR for long time. I'm sorry that I don't response about this PR.

What issue that you found in this PR? Do you need me to do something? I hope this PR can merge.

**Comment by AdrienPoupa** [comment]
There is an issue with self joins

**Comment by yajra** [comment]
Released on v6.25.0 Thanks!

**Pull request merged**
