### PR TITLE
feat(relations): add support for HasOneThrough

### PR DESCRIPTION
**Pull request by warlof**
This pull request add support for HasOneThrough relationship.

I hope I did it well since I'm not fluent at all with that kind of Laravel relation.
However, it sounds working well into my project ^^'

### CODE REVIEW

**Comment by yajra** [comment]
@warlof the PR looks great thanks! 

Question: Do you know what version of Laravel started the support for HasOneThrough? I'm a bit outdated atm. Thanks!

**Comment by yajra** [comment]
Checking Laravel docs and seems like it was documented since 5.8. I guess this is safe to merge since v9 supports 5.8 & above. Will wait a day incase someone wants to review. Looks good to go for me. Thanks!

**Comment by warlof** [comment]
I confirm, that kind of relation spawn in Laravel 5.8.

https://github.com/laravel/framework/blob/5.8/src/Illuminate/Database/Eloquent/Relations/HasOneThrough.php

**Comment by yajra** [comment]
Released on v9.10.0, thanks!

**Comment by warlof** [comment]
thank you for your amazing factory :)

**Pull request merged**
