### PR TITLE
[6.0] Support nested search #841

### PR DESCRIPTION
**Pull request by yajra**
Cherry pick of #841.

### CODE REVIEW

**Comment by yajra** [comment]
Validating againsts the demo application and it works perfectly. Thanks @ethaizone for this contribution. 💯

**Comment by yajra** [comment]
Fixes the following issues: #696, #789, #771, #509, #441

**Comment by ethaizone** [comment]
@yajra Oh. So many issue that this pull request can fix. Wow.

**Comment by yajra** [comment]
I just added some docs for this [here](https://yajrabox.com/docs/laravel-datatables/6.0/relationships). If I missed something, feel free to submit docs too at the [docs repo](https://github.com/yajra/laravel-datatables-docs). Thanks!

**Comment by spescina** [comment]
global search and order by in nested relations does not work in 6.22.5.

**Comment by spescina** [comment]
I am pretty sure that the bug affects only self nested relations, in ex. **post.category.parent**

**Comment by yajra** [comment]
@spescina Yes, self join queries was confirmed bug on issue #880. For ordering, there is a pending [PR](https://github.com/yajra/laravel-datatables/pull/850) that tries to address this but I found an issue on it during testing. Still working on it and can't give a target date yet.

**Comment by rzb** [comment]
It would be nice if you included an example of nested relationships using the service approach to the docs. I keep getting `Call to undefined method Illuminate\Database\Query\Builder::model.nestedModel()`

**Pull request merged**
