### PR TITLE
Added ability to pass an array of needed columns and get only them in response, to not add or remove them one by one

### PR DESCRIPTION
**Pull request by ptuchik**
Example `DataTables::of($items)->only(['id', 'name'])->make(true)`

### CODE REVIEW

**Comment by yajra** [comment]
The idea looks fine. Can you please remove the new line on doc blocks. Thanks!

**Comment by ptuchik** [comment]
> The idea looks fine. Can you please remove the new line on doc blocks. Thanks!

Thanks for approving the idea. I have removed the new lines in doc blocks

**Comment by ptuchik** [comment]
Hi, are there any updates? I really need this. Thank you

**Comment by yajra** [comment]
Released on v8.9.0 🚀 thanks!

**Comment by yajra** [comment]
BTW, if you can, please submit also a PR on [docs](https://github.com/yajra/laravel-datatables-docs) and a tests if possible. 🍻

**Comment by ptuchik** [comment]
Thank you for update, I will create docs and tests PR

**Pull request merged**
