### PR TITLE
[7.0] Implement multi-term smart search in QueryBuilderEngine.

### PR DESCRIPTION
**Pull request by apreiml**
This pr tries to solve the smart search feature #1109 . The idea for the requested change is from my colleague.

if this solution is preferable I'd also try to implement smart search for the collection engine.

### CODE REVIEW

**Comment by yajra** [comment]
Wow, nice PR and looks good. 💯 

Please go ahead and do the same for collection engine :). Will test and review this as soon as I can. Thanks!

**Comment by apreiml** [comment]
Smart search is now also implemented for the CollectionEngine. It is now also disabled if smart is set to false.

One thing that still bugs me though is, that QueryBuilder doesn't wrap the string with '%', smart search is disabled. The CollectionEngine on the other hand uses string contains, which has similar functionality as wrapping the string with '%' and using `like` in a query. So it behaves like the old smart search, even if smart search is disabled.

Do you want to really omit the '%', if smart search is disabled? Or does the CollectionEngine need to match the collumns exactly, if smart search is disabled?

**Comment by yajra** [comment]
@apreiml thanks for the updates and can you please create a separate PR for collection engine for easier testing and reviewing.

With regard to collection, I honestly rarely use collection and haven't give it so much attention. Will give it a further digging once I had the chance to review your PR. Thanks a lot!

**Comment by yajra** [comment]
Released on v7.4.0 🚀 along with collection engine. This is indeed a great addition, thanks a lot! ❤️

**Pull request merged**
