### PR TITLE
[6.0] Added code for generating editor script

### PR DESCRIPTION
**Pull request by karmendra**
This Code change was done long back when I was trying to use editor along with datatables. I know version 8.0 includes dataTables editor but i was wondering if we can implement the same in version 6.0.

How it works is instead of writing javascript for editor in the blade file, user can key in details of editor in an array in getBuilderParameters() function as following:

    /**
     * Get default builder parameters.
     *
     * @return array
     */
    protected function getBuilderParameters()
    {
	    return [
		    'order'      => [[4, "asc"]],
		    'dom'        => '<"row"<"col-md-2"l><"col-md-4"B><""p>><"row"<"col-sm-12"tr>><"row"<"col-sm-5"i><"col-sm-7"p>>',
		    'buttons'    => [
			    'selectAll', 'selectNone', 'export', 'print', 'reset', 'reload',
			    ['extend' => 'create', 'editor' => 'editor'],
			    ['extend' => 'edit', 'editor' => 'editor'],
			    ['extend' => 'selectedSingle', 'text' => 'Duplicate'],
		    ],
		    'select'     => [
			    'style'    => 'multi',
			    'selector' => 'tr',
		    ],
		    'keys'       => [
			    'columns' => ':not(:first-child)',
			    'keys'    => [9],
		    ],
		    'rowId'      => 'id',
		    'responsive' => true,
		    'editor'     => [
			    'variable' => 'editor',
			    'ajax'     => [
				    'url'     => route('user.editor'),
				    'headers' => [
					    'X-CSRF-TOKEN' => '$(\'meta[name="csrf-token"]\') . attr(\'content\')',
				    ],
			    ],
			    'idSrc'    => 'mtdr_id',
			    'fields'   => [
				    ['label' => 'User Name', 'name' => 'name', 'def' => 1, 'type' => 'readonly'],
				    [
					    'label'   => 'User Type', 'name' => 'type',
					    'type'    => 'select',
					    'options' => ['Admin' => 'Admin', 'User' => 'User'],
				    ],
				    [
					    ['label' => 'Email', 'name' => 'email'],
					    [
						    'label'   => 'Enabled', 'name' => 'enabled', 'type' => 'select',
						    'options' => ['n' => 'n', 'y' => 'y'],
					    ],
				    ],
			    ],
		    ],
	    ];
    }

### CODE REVIEW

**Comment by yajra** [comment]
v6.0 is kinda old and I may not be able to test this. Though the PR looks fine. 

Anyways, can you confirm first that this working well on your side? I will trust your judgement on this one. Thanks!

**Comment by karmendra** [comment]
So, I had been using this for a very long time in my production via vcs setup, and I confirm this is working well on my side. Please consider merging this.

**Comment by karmendra** [comment]
Any plans on merging this?

**Comment by yajra** [comment]
Sorry but I am not using v6.0 anymore so I am not able to test this further. Can you confirm if this working well. I can merge if you give me your assurance :). Thanks!

**Pull request closed without merging**
