### PR TITLE
[6.0] Add multiple transformer ability

### PR DESCRIPTION
**Pull request by scs75**
In my scenario I have to separate general and unique transformation. So I implement multiple transformation ability in BaseEngine class. You can use like:

```
return $this->datatables
->eloquent($this->query())
->addTransformer(new GeneralTransformer($columnDefinitions))
->addTransformer(new OrderTransformer())
->make(true);

```

I keeped the setTransformer api for backward compatibility.

### CODE REVIEW

**Comment by yajra** [comment]
Looks good! Will try to test/review this asap. Thanks!

**Comment by yajra** [comment]
@scs75 would you mind sharing your `GeneralTransformer` code or explain how it works? Trying to test this PR now. Thanks!

**Comment by scs75** [comment]
[http://pastebin.com/HRR8n3fr](http://pastebin.com/HRR8n3fr)

**Comment by scs75** [comment]
My goal was: make automatic transformation based on column type.
The constructor parameter is an own table fields array which is an abstraction above the column definition in DataTable->getColumns().

**Comment by yajra** [comment]
Sorry for not having the time to look at this. I'm not using fractal much so it's been out of my focus. If you still want to push this request. I would gladly review it on the new package https://github.com/yajra/laravel-datatables-fractal where fractal integration was extracted. Thanks!

**Pull request closed without merging**
