### PR TITLE
[8.0] Fixes from PHPStan

### PR DESCRIPTION
**Pull request by carusogabriel**
After run [`PHPStan`](https://github.com/phpstan/phpstan) up to level 5, some code could get improved in Laravel Datatables :smile:

### CODE REVIEW

**Comment by yajra** [comment]
Nice, thanks for introducing phpstan, this is the first time I heard about it and looks like a great utility. Will try this also on my other packages. :)

**Comment by carusogabriel** [comment]
If you want, I can add `PHPStan` to our `Travis CI` to detect this misses :)

**Comment by yajra** [comment]
That sounds interesting, can you please do submit a PR for travis for me to see how it works? :)

**Comment by carusogabriel** [comment]
I'll just wait for https://github.com/Weebly/phpstan-laravel/pull/1 to fix some [Laravel magic calls](https://github.com/phpstan/phpstan#extensibility)

**Pull request merged**
