### PR TITLE
Fix ambiguous column 'deleted_at'

### PR DESCRIPTION
**Pull request by cuatao**
Fix error ambiguous when two tables are using SoftDeletes.

### CODE REVIEW

**Comment by vaanholtje** [comment]
When can we expect this fix to be released?

**Comment by yajra** [comment]
Duplicate of #1688, can't check test the PR yet. Can you please check and confirm a feedback. Will merge if it passes for you.

**Comment by vaanholtje** [comment]
Tested both and both seem to fix the issue think #1688 is a cleanir fix

**Comment by cuatao** [comment]
@yajra Tested #1688, it's ok. I think #1668 is cleaner, so I closed my PR.

**Pull request closed without merging**
