### PR TITLE
For laravel 5.6

### PR DESCRIPTION
**Pull request by lloricode**
:)

### CODE REVIEW

**Comment by mseymour** [comment]
You're a little late there. #1609

**Comment by lloricode** [comment]
@mseymour it's ok :D

**Comment by yajra** [comment]
Thanks!

**Comment by webmake** [comment]
When can we expect **stable** release tag for this? I see 2issues and 2pr's created for **same problem** :) Because we can't update due `"prefer-stable": true` in third party dependencies, when requiring `dev-master`...

https://github.com/yajra/laravel-datatables/issues/1617
https://github.com/yajra/laravel-datatables/issues/1568

**Pull request closed without merging**
