### PR TITLE
the proper way to fix addColumn Bug

### PR DESCRIPTION
**Pull request by openvast**
issue url
https://github.com/yajra/laravel-datatables/issues/157

### CODE REVIEW

**Comment by yajra** [comment]
I just tested this PR and searching and ordering is still not working when addColumn was used. See attached screenshot. I added an action column with a value of test.

screen shot 2015-08-29 at 4 04 32 pm

```
ErrorException in BaseEngine.php line 245:
Undefined offset: 5
```

**Comment by openvast** [comment]
you test this

        return $this->request->columnName($column) ?: (isset($this->columns[$column]) ? $this->columns[$column] : $this->columns[0]);

**Comment by openvast** [comment]
i can't upload images.can you give an  email to sent you ?

**Comment by yajra** [comment]
Still not working. The error now is. My email is aqangeles@gmail.com
```
SQLSTATE[42S22]: Column not found: 1054 Unknown column 'action' in 'where clause' (SQL: select count(*) as aggregate from (select '1' as row_count from `users` where (LOWER(`id`) LIKE %test% or LOWER(`name`) LIKE %test% or LOWER(`email`) LIKE %test% or LOWER(`created_at`) LIKE %test% or LOWER(`updated_at`) LIKE %test% or LOWER(`action`) LIKE %test%)) count_row_table)
```

**Comment by openvast** [comment]
i send an email to you

**Comment by yajra** [comment]
I see. You are just using the `make()` method. Your code works on array response but not on object response. Try using `make(true)` approach. The fix should work on both cases.

**Comment by openvast** [comment]
hah, you right.wait me to try using make(true)

**Comment by yajra** [comment]
Surely. I will keep this PR open. Thanks for the help.

**Comment by openvast** [comment]
i don't have Documentation for this program ,so, i must to spend long time to see the code and  test, test ..  .finally,i success to fix addColumn bug. can you give me a Documentation for your datatables ? 

 /**
     * Get column name by order column index.
     *
     * @param int $column
     * @return mixed
     */
    protected function getColumnName($column)
    {
        $name = $this->request->columnName($column) ?: (isset($this->columns[$column]) ? $this->columns[$column] : $this->columns[0]);
        return in_array($name, $this->sColumns, true) ? $this->columns[0] : $name;
//        return $this->request->columnName($column) ?: $this->columns[$column];
//        return $this->request->columnName($column) ?: (isset($this->columns[$column]) ? $this->columns[$column] : $this->columns[0]);
    }

and then, don't laugh my english bad.can you teach me how to say english?give me a url or email...something to Improve English .thanks

**Comment by yajra** [comment]
Cool and thanks! Released on v5.11.4. Cheers ^_^.

**Comment by openvast** [comment]
Cheers ^_^.

**Pull request merged**
