### PR TITLE
Readme: implictly set "--provider" when publishing

### PR DESCRIPTION
**Pull request by uniconstructor**
"--provider" wiil prevent you from accidentally publishing content from other service providers

### CODE REVIEW

**Comment by yajra** [comment]
If we will use the provider flag, then I guess we can remove `--tag=datatables` since it's basically doing the same task.

**Comment by yajra** [comment]
On the other hand, don't you think that it's easier to remember the tags than using the provider?

**Comment by uniconstructor** [comment]
Yes, I think that remove `--tag=datatables` is a good idea.
About tag vs provider option: yes tag is simpler to remember, but DataTables is a very popular plugin and there is a chance that some other Laravel package will use `--tag=datatables` for resource publishing.
To be honest, chances of tag name collision is not very high here, but I prefer to prevent it completely.

**Comment by yajra** [comment]
Good point on possibility of name collision. Thanks!

**Pull request merged**
