### PR TITLE
[7.0] Fixed a bug for "undefined index" errors.

### PR DESCRIPTION
**Pull request by redelschaap**
Fixed a bug for "undefined index" errors

### CODE REVIEW

**Comment by yajra** [comment]
@redelschaap what version are you using? I think this can be targeted on the latest version 8.0? Thanks!

**Comment by redelschaap** [comment]
I'm using 7.0. I fixed it in `src/Helper.php`, which is not available in 8.0.

**Comment by yajra** [comment]
Released on v7.10.2, thanks!

**Comment by redelschaap** [comment]
Great! You're welcome.

**Comment by blasterweb** [comment]
When will this be implemented on 8.0?

**Comment by yajra** [comment]
@blasterweb as per @redelschaap, this is not applicable on v8. Are you having the same issue? If yes, can you please provide some code to reproduce it? Thanks!

**Comment by redelschaap** [comment]
I noticed the exact same function exists in v8, the file was just moved. I created a PR: https://github.com/yajra/laravel-datatables/pull/1728

**Comment by blasterweb** [comment]
@yajra, the hint from @redelschaap worked for me.

**Pull request merged**
