### PR TITLE
Ensure dates are not turned to arrays by processor

### LINKED ISSUE #3156: Handle DateTime values better
### Summary of problem or feature request
In the [`Helper::transformRow()` method](https://github.com/yajra/laravel-datatables/blob/master/src/Utilities/Helper.php#L229) there is special code for nicely formatting a `DateTime` object into a string value. However, "processing" is done before "transforming" so the [`Helper::convertToArray()` method](https://github.com/yajra/laravel-datatables/blob/master/src/Utilities/Helper.php#L204) has already converted all `DateTime`s into arrays.

### Code snippet of problem
```php
$data = [["a_date" => new DateTime()], ["a_date" => new DateTime('tomorrow')]];
$table = Yajra\DataTables\Facades\DataTables::collection($data)->make();
dump($table);
```
This results in something like this:
```none
= Illuminate\Http\JsonResponse {#6936
    +headers: Symfony\Component\HttpFoundation\ResponseHeaderBag {#6935},
    +original: [
      "draw" => 0,
      "recordsTotal" => 2,
      "recordsFiltered" => 2,
      "data" => [
        [
          "a_date" => [
            "date" => "2024-07-05 17:06:52.608468",
            "timezone_type" => 3,
            "timezone" => "America/Toronto",
          ],
        ],
        [
          "a_date" => [
            "date" => "2024-07-06 00:00:00.000000",
            "timezone_type" => 3,
            "timezone" => "America/Toronto",
          ],
        ],
      ],
      "input" => [],
    ],
    +exception: null,
  }
```
Where I think the intent (based on the code in `Helper::transformRow()`) is something like this:
```none
= Illuminate\Http\JsonResponse {#6936
    +headers: Symfony\Component\HttpFoundation\ResponseHeaderBag {#6935},
    +original: [
      "draw" => 0,
      "recordsTotal" => 2,
      "recordsFiltered" => 2,
      "data" => [
        [
          "a_date" => "2024-07-05 17:06:52",
        ],
        [
          "a_date" => "2024-07-06 00:00:00",
        ],
      ],
      "input" => [],
    ],
    +exception: null,
  }
```
### System details
- PHP 8.3.8
- Laravel 11.14.0
- Laravel-Datatables 11.1.2

### PR DESCRIPTION
**Pull request by miken32**
Resolves #3156 and lets the transformer deal with date formatting as intended.

### CODE REVIEW

**Comment by yajra** [comment]
@miken32 the patch is intended for Collection, right? I tried using an Eloquent model with a date but the serialization is still the same and returns something like `2024-08-11T10:23:57.000000Z` where the expectation is `2024-08-11 10:23:57`.

**Comment by miken32** [comment]
The update was to the helper class so I would have expected it to apply to both, but I was unable to check with a query builder instance as easily.

**Comment by yajra** [comment]
The patch only applies to collection/array data sources. 

For Eloquent, it is converted to an array thus making the [model date serializer](https://github.com/yajra/laravel-datatables/pull/3163/files#diff-253f89e8a2576ce3d4f678ecfcb95ffa3f699e848e037cb1f0ff495aa937b953R204) take effect. This explains why we still get `2024-08-11T10:23:57.000000Z` when using an eloquent data source.

**Comment by yajra** [comment]
Release on https://github.com/yajra/laravel-datatables/releases/tag/v11.1.4, 🚀 Thanks!

**Pull request merged**
