### PR TITLE
#2593 constrained eager loading ordering

### PR DESCRIPTION
**Pull request by Sadikk**
See #2593

Feel free to close the PR if it's already supported in some way

### CODE REVIEW

**Comment by yajra** [comment]
Looks good, will try to check this as soon as I can. Thanks!

**Comment by victorelec14** [comment]
is there news about the merging of this PR? :)

**Comment by yajra** [comment]
Can't check this further yet and need help on reviewing the PR. Can anyone confirm that the PR works as stated? Will gladly merge this if anyone can confirm. Thanks!

**Comment by Sadikk** [comment]
I'm using this in production in my SaaS app and that works, if that can be a confirmation (but well, I'm the OP so)

**Comment by victorelec14** [comment]
hi i just tried with the modifications @Sadikk  made in the file "src/EloquentDataTable.php" but in my case it doesn't work. :/

old query (this sort does not work with the PR)
```
 public function query() {
        return Business::with('careType');
    }
```

normal method with joins, that if it works without the PR
```
public function query() {
        return Business::select(['business.*', 'care_types.name AS care_type_name'])
                    ->leftJoin('care_types', 'care_types.id','=','business.care_type_id');
    }
```

composer.json

```
"laravel/framework": "^8.40",
"laravel/jetstream": "^2.3",
"laravel/sanctum": "^2.6",
"laravel/tinker": "^2.5",
"yajra/laravel-datatables-oracle": "^9.18"
```

thanks!

**Comment by yajra** [comment]
I just tried to replicate this on latest version and it seems to have already been fixed. Thanks!

```php
    public function query(User $model): EloquentBuilder
    {
        return $model->newQuery()
                       ->with([
                           'roles' => function (Builder $q) {
                               $q->select('roles.id', 'roles.name')->where('roles.id', '>', 1);
                           },
                       ])
                       ->with('permissions:id,name')
                       ->withCount('permissions')
                       ->select('users.*');
```

**Pull request closed without merging**
