### PR TITLE
[10.x] Fix relation key name for BelongsToMany

### PR DESCRIPTION
**Pull request by RF1705**

### CODE REVIEW

**Comment by yajra** [comment]
Looks good but will it not break other relationships? Would it be possible to add a test for this? Thanks!

**Comment by OzanKurt** [comment]
@yajra It seems just created the exact same pull request. #2855 

Please merge this, this can't break anything since it doesn't do any assumptions. It just takes the value from the relationship object.

**Comment by yajra** [comment]
Released on https://github.com/yajra/laravel-datatables/releases/tag/v10.1.3. Thanks! 🚀

**Comment by OzanKurt** [comment]
Thanks a lot!

**Pull request merged**
