### PR TITLE
bug fixed: addColumn()

### PR DESCRIPTION
**Pull request by liub1993**
The function **addColumn()** would throw an exception if the newly added column name can not be found in MySQL table and the query still contains the column added by **addColumn( )**. 

So I just add the new column in the blacklist, and it works.

### CODE REVIEW

**Comment by liub1993** [comment]
Yes, it only fails when we use the QueryBuilderEngine.

**Comment by yajra** [comment]
Maybe we can put `addColumn` override inside `QueryBuilderEngine`. `addToBlacklist` can stay on `BaseEngine`.

Anyways, will review/test this asap. Thanks!

**Comment by yajra** [comment]
BTW, please format the code to PSR-2.

**Comment by liub1993** [comment]
Sorry for my mistake, and thanks for your great work!

**Comment by liub1993** [comment]
Hi, @yajra , I have: 
1. Renamed the  `addToBlacklist`  to  `pushToBlacklist`  and removed the redundant code in the method;
2. Rewrote the `addColumn` in QueryBuilderEngine.php.

I don't know if there are any better solutions, forgive me for my pool programming ...

**Comment by yajra** [comment]
@liub1993 thanks for the updates. Will do some testing but we need to be careful on this. I just realized that this may cause some **breaking change** on some users like those who are using `filterColumn` api to override the default search for added columns.

P.S. 
Can you please commit only the methods (`pushToBlacklist` and `addColumn`) affected by the updates?

**Comment by yajra** [comment]
Nvm my previous comment. Merging and will do the necessary adjustments to fix the potential breaking change on #1169. Thanks!

**Pull request merged**
