### PR TITLE
feat: recordsFiltered Limit (Hard Limit in Config)

### PR DESCRIPTION
**Pull request by saaiful**
Hard Limit in Config (for Pagination)

Part 1 > Part 2 is in laravel-datatables-html https://github.com/yajra/laravel-datatables-html/pull/156

### CODE REVIEW

**Comment by mx-advaud** [comment]
This is very important. I would very much like to be able to use this feature.

**Comment by gemul** [comment]
Hi, when will this feature be implemented? This is rather high security risk for the server, where end user can arbitrarily set the "length" parameter to very large number upon request and lead to high load of the server.

**Comment by yajra** [comment]
My apologies for not being able to prioritize this. I tried changing the base to master but there seem to be conflicts.

Please submit a new PR or fix this if possible. Will also try to implement when I got the chance.

**Comment by gemul** [comment]
> My apologies for not being able to prioritize this. I tried changing the base to master but there seem to be conflicts.
> 
> Please submit a new PR or fix this if possible. Will also try to implement when I got the chance.

Hi, I've submitted a PR for this issue. Please take a look when you get a chance.

Let me know if you need any further adjustments!

#3171

**Comment by yajra** [comment]
I am closing this in favor of https://github.com/yajra/laravel-datatables/pull/3171, Thanks!

**Pull request closed without merging**
