### PR TITLE
New check for applied filter (#2841)

### PR DESCRIPTION
**Pull request by marcelhoogantink**
Here is my first PR for issue #2841

### CODE REVIEW

**Comment by yajra** [comment]
@marcelhoogantink great PR, almost there 🎊 . 

Can you please fix the failing static analysis and tests? StyleCI can be fixed later on and can be ignored. Thanks!

**Comment by marcelhoogantink** [comment]
The error in the static analysis are triggered on code I did not touch.
The last 3 errors in the tests are errors on tests that have a higher filteredRecords than totalRecords, so this test seems not logical to me.

**Comment by yajra** [comment]
Please fix at least the PHPUnit test for this to be merged. Thanks!

**Comment by marcelhoogantink** [comment]
Ok, I tried, but in my aproach, when there is no filter active, the recordsFiltered is equal to the recordsTotal.
In this situation the tests 'it_can_set_total_records' and 'it_can_set_zero_total_records' fails because the recordsFiltered is not relevant here.
Please reply ...

**Comment by marcelhoogantink** [comment]
To bad, no comment after may last question.
So no ibterersts?
I am closing the PR.

**Pull request closed without merging**
