### PR TITLE
Add laravel 5.8 support

### PR DESCRIPTION
**Pull request by lloricode**

### CODE REVIEW

**Comment by yajra** [comment]
Thanks, seems like there are some breaking changes on `BelongsTo::getQualifiedForeignKey()` and might need to bump a major version. Will try to work on this within the week.

**Comment by lloricode** [comment]
@yajra , yes that's the only failing

Thanks

**Comment by yajra** [comment]
@lloricode thanks, I copied some of your codes and released it on v9.0.

**Comment by lloricode** [comment]
no problem Thanks :)

**Pull request closed without merging**
