### PR TITLE
Separate builder script template to config

### PR DESCRIPTION
**Pull request by vladkucherov**

### CODE REVIEW

**Comment by vladkucherov** [comment]
@yajra The test doesn't pass because phpunit can't find the config for it, and in return, gets null. can you see why?

**Comment by yajra** [comment]
@vladkucherov, great PR :100: ! You need to mock the Config class to make the test pass. Or maybe just use `config()` function helper for easier mocking? Maybe something like below:

```php
// Builder.php
return sprintf(config('datatables.script_template'), $this->tableAttributes['id'], $parameters);

// tests/helper.php
function config($path) {
    switch($path) {
        case 'datatables.script_template':
            return '(function(window,$){window.LaravelDataTables=window.LaravelDataTables||{};window.LaravelDataTables["%1$s"]=$("#%1$s").DataTable(%2$s);})(window,jQuery);';
    }
}
```

On the other hand, I think we can also convert your PR and load a view instead? This way, we can also address issue #212. Something like:

```php
// Builder.php
return sprintf(
  $this->view->make(config('datatables.script_template', 'datatables::script'))->render(),
  $this->tableAttributes['id'], $parameters
);

// script.blade.php
(function(window,$){window.LaravelDataTables=window.LaravelDataTables||{};window.LaravelDataTables["%1$s"]=$("#%1$s").DataTable(%2$s);})(window,jQuery);

// config/datatables.php
'script_template' => 'datatables::script'
```

**Comment by yajra** [comment]
@vladkucherov, sorry for taking over your PR. I went ahead and implemented the solution I proposed where we use a blade template to be used for script. Credits to your idea on how implement custom template for js. 

Btw, if it's ok, can you please test the latest commit on develop/6.0 branch if it works for you? Thanks a lot!

**Comment by yajra** [comment]
Also, I've added a `setTemplate('path.to.view')` method, where we can override the default view to be used for js template. FYI.

```php
public function html()
    {
        return $this->builder()
            ->columns([
                'id',
                'name',
                'email',
                'created_at',
                'updated_at',
            ])
            ->parameters([
                'dom' => 'Bfrtip',
                'buttons' => ['csv', 'excel', 'pdf', 'print', 'reset', 'reload'],
            ])
            ->setTemplate('custom.script');
    }
```

**Comment by vladkucherov** [comment]
I tested it out, and looks fine now ! :+1:

**Pull request closed without merging**
