### PR TITLE
Preparation for laravel 8 support

### PR DESCRIPTION
**Pull request by lloricode**
Sept 8 is release of laravel 8,

### CODE REVIEW

**Comment by lloricode** [comment]
I just notice that orchestra is outdated, this need to update to version 6 to test for laravel 8

**Comment by yajra** [comment]
I will check this once the stable version is released.

**Comment by SudoGetBeer** [comment]
> I will check this once the stable version is released.

Just as a small notification: laravel 8 was just released  :wink:

**Comment by yajra** [comment]
Seems like there are no breaking changes that will affect the package. Released on v9.11.0. Thanks! 🚀

**Pull request merged**
